version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vsu_project
    ports:
      - "5432:5432"
    restart: always

  app:
    container_name: application
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8080
      DDL_AUTO: ${DDL_AUTO}
      SQL_INIT: ${SQL_INIT}
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    restart: always

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app